export interface XeblogConvProps {
  name: string;
  mood: string;
  children: HTMLElement[];
  standalone?: boolean;
  aiModel?: string;
}

const ConvSnippet = ({
  name,
  mood,
  children,
  standalone,
  aiModel,
}: XeblogConvProps) => {
  const nameLower = name.toLowerCase();
  name = name.replace(" ", "_");
  const size = standalone ? 256 : 128;

  return (
    <>
      <div className="my-4 flex space-x-4 rounded-md border border-solid border-fg-4 bg-bg-2 p-3 dark:border-fgDark-4 dark:bg-bgDark-2 max-w-full min-h-fit">
        <div className="flex max-h-16 shrink-0 items-center justify-center self-center">
          <img
            style={`max-height:${standalone ? "6" : "4"}rem`}
            alt={`${name} is ${mood}`}
            loading="lazy"
            src={`https://cdn.xeiaso.net/sticker/${nameLower}/${mood}/${size}`}
          />
        </div>
        <div className="convsnippet min-w-0 self-center">
          {"<"}
          <a href={`/characters#${nameLower}`}>
            <b>{name}</b>
          </a>
          {">"} {children}
          {aiModel && (
            <>
              <br />
              <small>Content generated by AI using the model {aiModel}.</small>
            </>
          )}
        </div>
      </div>
    </>
  );
};

export default ConvSnippet;
