// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login(discordInvite string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-screen flex items-center justify-center px-4\"><div class=\"max-w-md w-full bg-white dark:bg-slate-800/80 backdrop-blur-sm rounded-xl p-8 shadow-lg border border-gray-200 dark:border-slate-700\"><h1 class=\"text-2xl font-bold text-gray-900 dark:text-gray-100 mb-2\">Sponsor Panel</h1><p class=\"text-gray-600 dark:text-gray-300 mb-6\">Manage your sponsorship benefits</p><a href=\"/login\" class=\"block w-full bg-gray-900 dark:bg-orange-600 hover:bg-gray-800 dark:hover:bg-orange-700 text-white text-center py-3 rounded-lg mb-6 transition-colors\">Login with GitHub</a><div class=\"border-t border-gray-200 dark:border-slate-700 pt-4\"><h3 class=\"font-semibold text-gray-900 dark:text-gray-100 mb-2\">Benefits:</h3><ul class=\"text-sm text-gray-600 dark:text-gray-300 space-y-1\"><li>✓ All sponsors: Discord access</li><li>✓ $50+/month: Team invitations</li><li>✓ All sponsors: Logo submission</li></ul></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
