apiVersion: batch/v1
kind: Job
metadata:
  name: christinewebsite-ping
  namespace: apps
  labels:
    app: christinewebsite
spec:
  template:
    spec:
      containers:
      - name: ping-bing
        image: xena/alpine
        command:
          - "busybox"
          - "wget"
          - "-O"
          - "-"
          - "-q"
          - "https://www.bing.com/ping?sitemap=https://christine.website/sitemap.xml"
      - name: ping-google
        image: xena/alpine
        command:
          - "busybox"
          - "wget"
          - "-O"
          - "-"
          - "-q"
          - "https://www.google.com/ping?sitemap=https://christine.website/sitemap.xml"
      restartPolicy: Never
  backoffLimit: 4
