apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sponsor-panel-creds
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/lc5zo4zjz3if3mkeuhufjmgmui/items/Sponsor Panel Creds"
