export default {
  "CVE": "Vulnerability information and my responsible disclosures of said vulnerabilities.",
  "colemak": "My efforts at learning to type with colemak instead of qwerty.",
  "conlangs": "Information about constructed languages I've attempted to make.",
  "dreams": "My attempts to write about my dreams",
  "ethereum": "Why Ethereum doesn't work in the real world.",
  "flightJournal": "My Gemini posts, copied over to my blog for safe-keeping.",
  "freenode": "My lamentations about the collapse of the IRC network freenode.",
  "get-going": "Tutorials for the Go programming language.",
  "h": "Evolution of the h human/programming language.",
  "howto": "Instructions on how to do various things.",
  "keeb": "Keyboard reviews.",
  "magick": "Writeups on things I've learned on my trip through chaos magick.",
  "malto": "Stories from my constructed world Malto.",
  "medium-archive": "Articles from my attempt at making a Medium blog long ago.",
  "nix-flakes": "Instructions on how to use Nix flakes, a new way to use Nix in a more reproducible way.",
  "nixos": "Nix.",
  "olin": "My attempts at running WebAssembly on the server.",
  "plt": "The saga of plt.",
  "recipes": "Recipes for use in your kitchen presented in a no-bullshit fashion.",
  "reconlangmo": "More details on how I tried to make a language named L'ewa.",
  "reviews": "Reviews on various tech or media properties.",
  "revueBackup": "My revue posts converted to xesite posts.",
  "rust": "Rust.",
  "short-story": "Flash fiction stories I've written over the years",
  "site-to-site-wireguard": "Instructions on setting up your own VPN with WireGuard.",
  "site-update": "Updates on this website. These articles will contain details on how this website is changed, new things I'm cooking up with it or more.",
  "spellblade": "Sections of my web novel Spellblade.",
  "templeos": "Articles about TempleOS, a public domain operating system for AMD64 computers.",
  "thesource": "Expansions for my TTRPG The Source.",
  "twitter": "Lamentations on the death of Twitter, a microblogging community.",
  "v": "The V programming language.",
  "vtuber": "My experience as a VTuber.",
  "waifud": "Information about my VM manager waifud.",
  "when-then-zen": "Meditation information sans bullshit.",
  "xeact": "Xeact, the best frontend femtoframework in the galaxy"
}