apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: xe-site-build-test-deploy
  namespace: ci

spec:
  description: |
    The CI/CD pipeline for xeiaso.net
  params:
    - name: repo-url
      type: string
      description: "Git repo to clone"
      default: "https://tangled.org/xeiaso.net/site"
    - name: "branch"
      type: string
      description: "Git branch to operate against"
    - name: "commit"
      type: string
      description: "Git revision to check out"
    - name: "actor"
      type: string
      description: "Tangled actor"
    - name: docker-image-base
      type: string
      description: string prefix for production docker images
      default: "registry.int.xeserv.us/xe/site"
  workspaces:
    - name: repo-data
      description: |
        Cloned repo files.
    - name: go-mod-cache
      description: |
        Go module cache
    - name: dockerconfig-atcr
      description: |
        Docker config for pushing images to atcr
  tasks:
    - name: fix-permissions
      taskRef:
        name: fix-permissions
      workspaces:
        - name: dir
          workspace: repo-data
    - name: clone-repo
      runAfter: ["fix-permissions"]
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: repo-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.commit)
    - name: docker-build-ci
      runAfter: ["clone-repo"]
      workspaces:
        - name: source
          workspace: repo-data
        - name: dockerconfig
          workspace: dockerconfig-atcr
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: registry.int.xeserv.us/xeiaso.net/site/ci:$(params.commit)
        - name: DOCKERFILE
          value: ./docker/ci-runtime.Dockerfile
        - name: EXTRA_ARGS
          value:
            [
              "--cache",
              "--cache-repo=registry.int.xeserv.us/xeiaso.net/site/ci/cache:latest",
              "--label=org.tangled.actor=$(params.actor)",
            ]
    - name: go-test
      runAfter: ["clone-repo", "docker-build-ci"]
      workspaces:
        - name: source
          workspace: repo-data
        - name: go-mod-cache
          workspace: go-mod-cache
      taskSpec:
        workspaces:
          - name: source
            mountPath: /src
          - name: go-mod-cache
            mountPath: /go
        steps:
          - name: go-test
            image: $(tasks.docker-build-ci.results.IMAGE_URL)@$(tasks.docker-build-ci.results.IMAGE_DIGEST)
            workingDir: $(workspaces.source.path)/repo
            script: |
              npm ci
              go mod download
              npm run generate
              go test ./...
          - name: validate-content-dates
            image: $(tasks.docker-build-ci.results.IMAGE_URL)@$(tasks.docker-build-ci.results.IMAGE_DIGEST)
            workingDir: $(workspaces.source.path)/repo
            script: |
              npm run validate-content-dates
    - name: patreon-saasproxy-build
      runAfter: ["go-test"]
      workspaces:
        - name: source
          workspace: repo-data
        - name: dockerconfig
          workspace: dockerconfig-atcr
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.docker-image-base)/patreon-saasproxy:latest
        - name: DOCKERFILE
          value: ./docker/patreon-saasproxy.Dockerfile
        - name: EXTRA_ARGS
          value:
            [
              "--destination=$(params.docker-image-base)/patreon-saasproxy:$(params.commit)",
              "--destination=$(params.docker-image-base)/patreon-sassproxy:$(params.branch)",
              "--label=org.tangled.actor=$(params.actor)",
            ]
    - name: sponsor-panel-build
      runAfter: ["go-test"]
      workspaces:
        - name: source
          workspace: repo-data
        - name: dockerconfig
          workspace: dockerconfig-atcr
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.docker-image-base)/sponsor-panel:latest
        - name: DOCKERFILE
          value: ./docker/sponsor-panel.Dockerfile
        - name: EXTRA_ARGS
          value:
            [
              "--destination=$(params.docker-image-base)/sponsor-panel:$(params.commit)",
              "--destination=$(params.docker-image-base)/sponsor-panel:$(params.branch)",
              "--label=org.tangled.actor=$(params.actor)",
            ]
    - name: xesite-build
      runAfter: ["go-test"]
      workspaces:
        - name: source
          workspace: repo-data
        - name: dockerconfig
          workspace: dockerconfig-atcr
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.docker-image-base)/bin:latest
        - name: DOCKERFILE
          value: ./docker/xesite.Dockerfile
        - name: EXTRA_ARGS
          value:
            [
              "--destination=$(params.docker-image-base)/site/bin:$(params.commit)",
              "--destination=$(params.docker-image-base)/bin:$(params.branch)",
              "--label=org.tangled.actor=$(params.actor)",
            ]
