// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: xesite.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "xeiaso.net/v4/pb/external/mi"
	protofeed "xeiaso.net/v4/pb/external/protofeed"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BuildInfo contains metadata about a build of the site.
type BuildInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The commit of Xe/site that was built
	Commit string `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	// When the site was last rebuilt
	BuildTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	// The version of Go running on the server
	GoVersion string `protobuf:"bytes,3,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	// The version of Deno used to build the site
	DenoVersion string `protobuf:"bytes,4,opt,name=deno_version,json=denoVersion,proto3" json:"deno_version,omitempty"`
	// The version of the xesite binary
	XesiteVersion string `protobuf:"bytes,5,opt,name=xesite_version,json=xesiteVersion,proto3" json:"xesite_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildInfo) Reset() {
	*x = BuildInfo{}
	mi := &file_xesite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildInfo) ProtoMessage() {}

func (x *BuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_xesite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildInfo.ProtoReflect.Descriptor instead.
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return file_xesite_proto_rawDescGZIP(), []int{0}
}

func (x *BuildInfo) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *BuildInfo) GetBuildTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BuildTime
	}
	return nil
}

func (x *BuildInfo) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *BuildInfo) GetDenoVersion() string {
	if x != nil {
		return x.DenoVersion
	}
	return ""
}

func (x *BuildInfo) GetXesiteVersion() string {
	if x != nil {
		return x.XesiteVersion
	}
	return ""
}

var File_xesite_proto protoreflect.FileDescriptor

const file_xesite_proto_rawDesc = "" +
	"\n" +
	"\fxesite.proto\x12\n" +
	"xeiaso.net\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11external/mi.proto\x1a\x18external/protofeed.proto\"\xc7\x01\n" +
	"\tBuildInfo\x12\x16\n" +
	"\x06commit\x18\x01 \x01(\tR\x06commit\x129\n" +
	"\n" +
	"build_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tbuildTime\x12\x1d\n" +
	"\n" +
	"go_version\x18\x03 \x01(\tR\tgoVersion\x12!\n" +
	"\fdeno_version\x18\x04 \x01(\tR\vdenoVersion\x12%\n" +
	"\x0exesite_version\x18\x05 \x01(\tR\rxesiteVersion2A\n" +
	"\x04Meta\x129\n" +
	"\bMetadata\x12\x16.google.protobuf.Empty\x1a\x15.xeiaso.net.BuildInfo26\n" +
	"\x04Feed\x12.\n" +
	"\x03Get\x12\x16.google.protobuf.Empty\x1a\x0f.protofeed.FeedB\x12Z\x10xeiaso.net/v4/pbb\x06proto3"

var (
	file_xesite_proto_rawDescOnce sync.Once
	file_xesite_proto_rawDescData []byte
)

func file_xesite_proto_rawDescGZIP() []byte {
	file_xesite_proto_rawDescOnce.Do(func() {
		file_xesite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xesite_proto_rawDesc), len(file_xesite_proto_rawDesc)))
	})
	return file_xesite_proto_rawDescData
}

var file_xesite_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xesite_proto_goTypes = []any{
	(*BuildInfo)(nil),             // 0: xeiaso.net.BuildInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 2: google.protobuf.Empty
	(*protofeed.Feed)(nil),        // 3: protofeed.Feed
}
var file_xesite_proto_depIdxs = []int32{
	1, // 0: xeiaso.net.BuildInfo.build_time:type_name -> google.protobuf.Timestamp
	2, // 1: xeiaso.net.Meta.Metadata:input_type -> google.protobuf.Empty
	2, // 2: xeiaso.net.Feed.Get:input_type -> google.protobuf.Empty
	0, // 3: xeiaso.net.Meta.Metadata:output_type -> xeiaso.net.BuildInfo
	3, // 4: xeiaso.net.Feed.Get:output_type -> protofeed.Feed
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xesite_proto_init() }
func file_xesite_proto_init() {
	if File_xesite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xesite_proto_rawDesc), len(file_xesite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_xesite_proto_goTypes,
		DependencyIndexes: file_xesite_proto_depIdxs,
		MessageInfos:      file_xesite_proto_msgTypes,
	}.Build()
	File_xesite_proto = out.File
	file_xesite_proto_goTypes = nil
	file_xesite_proto_depIdxs = nil
}
